### ISSUE TITLE
Multi-player games

### ISSUE THREAD

**Issue by wannabeCitizen** [QuantifiedSelfless/gulper#26]
Can we have the gulper handlers accept a list of of userid's so that we can request multiple players data in one request for a game.?

**Comment by mynameisfiber** [comment]
which processors would benefit from this and why is it better to do it in the backend than to launch multiple ajax queries?

**Comment by wannabeCitizen** [comment]
OwnUp, Romance, and Truth Game. It would allow us to have one point of failure in the game for hitting our server. Rather than an exhibit failing on one of four requests this will allow Ajax calls to be an all or nothing thing.

**Comment by mynameisfiber** [comment]
I think for the getting of data I'd prefer having it one user per request.  That being said, I added an endpoint to check if people have permissions to an exhibit and that can take however many users as you give it.

**Comment by wannabeCitizen** [comment]
Any reason for that preference? Doesn't increase likelihood of an exhibit having an error?

**Comment by mynameisfiber** [comment]
Well, we have 13 processors and making a special case for this seems a bit wasteful.  Especially since the only real way to comfortably have it work seamlessly with the other processors would require a change to the response format which would mean we'd have to modify the exhibits.

I just don't think the benefits outweigh the cost, especially since if our exhibits are failing at making 4 ajax queries vs 1 we have bigger things to worry about.

**Comment by mynameisfiber** [comment]
@wannabeCitizen i'm going to close this... reopen if you disagree
